### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by CHIAKI77** [CHIAKI77/furima-28774#9]
●フリマアプリのURL
https://furima-28774.herokuapp.com/

● Basic認証のIDとパスワード
ID:admin
パスワード:2222

● 出品者用のメールアドレスとパスワード
メールアドレス:test@test1
パスワード:test0000

● 購入者用のメールアドレスとパスワード
メールアドレス:test@test2
パスワード:aaaa0000

● 購入用カードの番号・期限・セキュリティコード
購入用カードの番号:4242424242424242
期限:12月24年
セキュリティコード:123

ご確認お願い致します。

**Comment by mc-nakayama** [comment]
吉田千秋さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
